### ISSUE TITLE
Data structure for main parts

### ISSUE THREAD

**Issue by grzanka** [APTG/2022_DCPT_LET#2]
- `/data/resources` -> common stuff like beam model, DICOM files etc
- `/data/fluka/input`  (`topas`, `phits`) -> input files for the MC codes
- `/data/fluka/results` -> collection of results from simulation (small files!)
- `/notebooks/` - Jupyter notebooks for analysis data from individual simulations and also for comparing various codes
- `/references/` - PDFs of important publictions, codes manuals 
- `/reports/figures` - PNGs and documents with summaries/reports

**Comment by nbassler** [comment]
https://drivendata.github.io/cookiecutter-data-science/

**Comment by nbassler** [comment]
how to deal with multiple instiutions providing different input for the same codes?
