### ISSUE TITLE
generate particle lists using SH12A

### ISSUE THREAD

**Issue by nbassler** [APTG/2022_DCPT_LET#41]
question: where to store .bdo files? These may get large, and should not be committed here.

**Comment by grzanka** [comment]
I have some storage on cyfronet S3 space
https://guide.s3p.cloud.cyfronet.pl/quickstart_en.html

**Comment by nbassler** [comment]
Could also host it privately. I checked university solutions, strange I didn't find any good solution. Will ask IT department.
