### ISSUE TITLE
Scoring out-of-field for Timepix

### ISSUE THREAD

**Issue by mdsainth** [APTG/2022_DCPT_LET#42]
MiniPIX was placed out iof the field at
Pos2  edge at 6 cm from the field edge (see picture 'TimepixPosition')
Pos3 edge at 0 cm from edge of the field  (see picture 'TimepixPosition')

Would it be possible to score LETf and LETd of protons in the detector plane from the detectors edge in 1mm bins (200bins up to 2cm in the detector plane) see picture 'TimepixPosition' for pos2 and pos3.

This would be needed for the following plans
Plan2 (160MeV) @2cm depth - lat pos2

Plan1 (No SOBP but only 149 MeV layer because we used research mode to lower intensity) 
@15cm - lat pos 2
@15.2cm - lat pos 2
@15.7cm  - lat pos3

**Comment by nbassler** [comment]
Yes, will take a look :)
Picture was not uploaded here? (you can drag and drop it into the text field)

**Comment by mdsainth** [comment]
![TimepixPositions](https://github.com/APTG/2022_DCPT_LET/assets/75473791/7a37ae9e-1cf0-4f38-b48b-3d8d11cd4213)

**Comment by nbassler** [comment]
It seems this deviates from standard setup, do I assume correctly, that the PMMA plate was remove entirely?
So for plan 2 (160 MeV mono) you say 2 cm depth, not 2.25 cm? 

Plan 1, depth 15.2 cm depth in solid water would then correspond to nominal **Plan 1c**, but without PMMA plate, 
Plan 1, depth 15.0 cm depth in solid water would then correspond to nominal **Plan 1b**, but without PMMA plate
Plan 1, depth 15.7 cm depth in solid water is a special config. Also without the PMMA plate.

And then, all was 149 MeV Monoenergetic. I need to check with Anne or Lilka if there was a plan for this.

Now, what to do, I am tempted to setup the nominal case including the 0.5 cm PMMA plate as target, but just going laterally as described above. Scoring region would then be the first 2 mm, **starting* at the indicated depths. Could maybe also reduce to 1 mm if requested.

Later, derived from the nominal case, one can make a detector-specific setup where the detector material and geometry is included in setup as well to some extend. I still think we should clearly distinguish of the nominal and the detector-simulation case. (Just a reminder to myself: We want to know what the LET is in a patient, and not in an artificial detector setup. How similar these can be for various detector systems is part of this task. :-)

All these would go into a separate dedicated minipix directory.

**Comment by mdsainth** [comment]
> 

PMMA plate was not removed, an example is added (pos 2a). 
The depth in solid water mentioned before just refers to the depth in the set-up as we used it for the other systems. 

149MeV was chosen as we moved to research mode to reduce the intensity and then we just used a single energy layer corresponding to the last layer in the SOBP. There was a reason on why an SOBP could not be delivered in this mode and I believe it was related to the uncertainties associated to the beam delivery (but I am not sure anymore). 
This was also the reason why we did not measure in the middle of the SOBP and were limited to position.

For me your approach is fine, there is now no reason to make the bins smaller and the detector itself does not need to be modeled.

Thanks!

**Comment by mdsainth** [comment]
![Pos2b](https://github.com/APTG/2022_DCPT_LET/assets/75473791/1c3a8345-297d-4461-ba5f-ac09c24c370b)

**Comment by mdsainth** [comment]
![Pos1b](https://github.com/APTG/2022_DCPT_LET/assets/75473791/18d13d23-d8eb-4b9d-be31-e230812e3b47)

**Comment by nbassler** [comment]
Very good, figure and photo is very helpful, thanks. :)
I also received the DICOM plans meanwhile, they are already uploaded in the "42-scoring-out-of-field-for-timepix" branch.

**Comment by nbassler** [comment]
since the geometry is significantly different than the orignial one, a new repository was made.
please see https://github.com/APTG/2022_DCPT_LET_timepix
closing it in this repo.
